openapi: 3.0.3
info:
  title: Common Schema Definitions
  description: Common schema definitions for reuse across API specifications
  version: 1.0.0

tags:
  - name: common
servers:
  - url: http://localhost:8080
paths: {}

components:
  schemas:
    ClassifiedCategory:
      type: string
      enum:
        - REAL_ESTATE
        - VEHICLE
        - SHOPPING
        - OTHER
      description: Category of the classified ad

    ClassifiedStatus:
      type: string
      enum:
        - PENDING_APPROVAL
        - ACTIVE
        - INACTIVE
        - DUPLICATE
        - EXPIRED
      description: Status of the classified ad

    ErrorResponse:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: integer
          format: int32
          description: HTTP status code
          example: 400
        message:
          type: string
          description: Error message
          example: "Invalid request parameters"
        details:
          type: string
          description: Detailed error information
          example: "Parameter must be a valid string"
        timestamp:
          type: string
          format: date-time
          description: Time when the error occurred
          example: "2025-04-26T10:30:00Z"